import { colorWrapper } from '@learnbase-ui/global/constant';
import { cva } from 'cva';

export const textStyles = cva('text-black', {
  variants: {
    color: colorWrapper('text'),
    fontStyle: {
      normal: 'font-normal',
      italic: 'italic',
    },
    fontWeight: {
      thin: 'font-thin',
      extraLight: 'font-extralight',
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semiBold: 'font-semibold',
      bold: 'font-bold',
      extraBold: 'font-extrabold',
      black: 'font-black',
    },
    size: {
      xs: 'text-xs leading-body-xs',
      sm: 'text-sm leading-body-sm',
      md: 'text-md leading-body-md',
      lg: 'text-lg leading-body-lg',
      xl: 'text-xl leading-body-xl',
      '2xl': 'text-2xl leading-body-2xl',
      '3xl': 'text-3xl leading-body-3xl',
      '4xl': 'text-4xl leading-body-4xl',
      '5xl': 'text-5xl leading-body-5xl',
    },
    textOverflow: {
      clip: 'overflow-clip',
      ellipsis: 'overflow-ellipsis',
      truncate: 'overflow-hidden whitespace-nowrap',
    },
    textTransform: {
      capitalize: 'capitalize',
      lowercase: 'lowercase',
      normal: 'normal-case',
      uppercase: 'uppercase',
    },
    verticalAlign: {
      baseline: 'align-baseline',
      top: 'align-top',
      middle: 'align-middle',
      bottom: 'align-bottom',
      textTop: 'align-text-top',
      textBottom: 'align-text-bottom',
      sub: 'align-sub',
      super: 'align-super',
    },
    textDecoration: {
      underline: 'underline',
      overline: 'overline',
      lineThrough: 'line-through',
      none: 'no-underline',
    },
    textAlign: {
      left: 'text-left',
      right: 'text-right',
      center: 'text-center',
      justify: 'text-justify',
      start: 'text-start',
      end: 'text-end',
    },
    letterSpacing: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    listStyleType: {
      none: 'list-none',
      disc: 'list-disc',
      circle: 'list-circle',
      square: 'list-square',
      decimal: 'list-decimal',
    },
    fontVariantNumeric: {
      normal: 'normal-nums',
      ordinal: 'ordinal',
      slashedZero: 'slashed-zero',
      lining: 'lining-nums',
      oldstyle: 'oldstyle-nums',
      proportional: 'proportional-nums',
      tabular: 'tabular-nums',
      diagonalFractions: 'diagonal-fractions',
      stackedFractions: 'stacked-fractions',
    },
  },
  defaultVariants: {
    color: 'primary',
    fontStyle: 'normal',
    fontWeight: 'normal',
    size: 'md',
    textOverflow: 'clip',
    textTransform: 'normal',
    verticalAlign: 'baseline',
    textDecoration: 'none',
    textAlign: 'left',
    letterSpacing: 'normal',
    listStyleType: 'none',
    fontVariantNumeric: 'normal',
  },
});
